import { Keyboard } from 'grammy';
import moment from 'moment';

export const dateKeyboard = new Keyboard()
  .text(moment().format('DD.MM.YYYY (ddd)'))
  .text(moment().add(1, 'days').format('DD.MM.YYYY (ddd)'))
  .text(moment().add(2, 'days').format('DD.MM.YYYY (ddd)'))
  .row()
  .text(moment().add(3, 'days').format('DD.MM.YYYY (ddd)'))
  .text(moment().add(4, 'days').format('DD.MM.YYYY (ddd)'))
  .text(moment().add(5, 'days').format('DD.MM.YYYY (ddd)'))
  .row()
  .text(moment().add(6, 'days').format('DD.MM.YYYY (ddd)'))
  .text(moment().add(7, 'days').format('DD.MM.YYYY (ddd)'));

export const hourKeyboard = new Keyboard()
  .text('8')
  .text('9')
  .text('10')
  .text('11')
  .row()
  .text('12')
  .text('13')
  .text('14')
  .text('15')
  .row()
  .text('16')
  .text('17')
  .text('18')
  .text('19')
  .row()
  .text('20')
  .text('21')
  .text('22')
  .text('23');

export const minuteKeyboard = new Keyboard()
  .text('00')
  .text('05')
  .text('10')
  .text('15')
  .row()
  .text('20')
  .text('25')
  .text('30')
  .text('35')
  .row()
  .text('40')
  .text('45')
  .text('50')
  .text('55');
